# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Exercise.create([
  { :title => "Fool's mate", :description => "http://en.wikipedia.org/wiki/Fool%27s_Mate", :start => "a8-black-♜,b8-black-♞,c8-black-♝,d8-black-♛,e8-black-♚,f8-black-♝,g8-black-♞,h8-black-♜,a7-black-♟,b7-black-♟,c7-black-♟,d7-black-♟,e7-black-♟,f7-black-♟,g7-black-♟,h7-black-♟,a2-white-♟,b2-white-♟,c2-white-♟,d2-white-♟,e2-white-♟,f2-white-♟,g2-white-♟,h2-white-♟,a1-white-♜,b1-white-♞,c1-white-♝,d1-white-♛,e1-white-♚,f1-white-♝,g1-white-♞,h1-white-♜", :lesson_id => 2, :created_at => "2012-11-09 22:07:09", :updated_at => "2013-02-15 02:51:25", :nextExercise => "undefined", :sortForLesson => 2 }
], :without_protection => true )



Lesson.create([
  { :title => "Basic Mates", :description => "Some simple Checkmates", :created_at => "2012-11-30 04:23:23", :updated_at => "2012-11-30 04:23:23" }
], :without_protection => true )

Move.create([
  { :piece_white => "♟", :starting_coordinate_white => "e2", :ending_coordinate_white => "e4", :explanation => "First set of moves!", :exercise_id => 2, :move_number => 1, :computer => nil, :created_at => "2012-11-12 01:33:04", :updated_at => "2013-02-20 22:06:21", :piece_black => "♟", :starting_coordinate_black => "e7", :ending_coordinate_black => "e5" },
  { :piece_white => "♛", :starting_coordinate_white => "d1", :ending_coordinate_white => "h5", :explanation => "Queen goes from d1 to h5", :exercise_id => 2, :move_number => 2, :computer => nil, :created_at => "2012-11-12 21:06:27", :updated_at => "2013-02-22 04:23:31", :piece_black => "♞", :starting_coordinate_black => "b8", :ending_coordinate_black => "c6" },
  { :piece_white => "♝", :starting_coordinate_white => "f1", :ending_coordinate_white => "c4", :explanation => "Bishop goes f1 to c4", :exercise_id => 2, :move_number => 3, :computer => nil, :created_at => "2012-11-12 21:07:35", :updated_at => "2013-02-22 04:24:23", :piece_black => "♞", :starting_coordinate_black => "g8", :ending_coordinate_black => "f6" },
  { :piece_white => "♛", :starting_coordinate_white => "h5", :ending_coordinate_white => "f7", :explanation => "Queen goes h5 to f7 for checkmate", :exercise_id => 2, :move_number => 5, :computer => nil, :created_at => "2012-11-12 21:08:31", :updated_at => "2013-02-22 05:17:51", :piece_black => "...", :starting_coordinate_black => "", :ending_coordinate_black => "" }
], :without_protection => true )



Role.create([
  { :name => "admin", :resource_id => nil, :resource_type => nil, :created_at => "2013-01-27 23:28:31", :updated_at => "2013-01-27 23:28:31" },
  { :name => "silver", :resource_id => nil, :resource_type => nil, :created_at => "2013-01-27 23:28:31", :updated_at => "2013-01-27 23:28:31" },
  { :name => "gold", :resource_id => nil, :resource_type => nil, :created_at => "2013-01-27 23:28:31", :updated_at => "2013-01-27 23:28:31" },
  { :name => "platinum", :resource_id => nil, :resource_type => nil, :created_at => "2013-01-27 23:28:31", :updated_at => "2013-01-27 23:28:31" }
], :without_protection => true )



User.create([
  { :email => "user@example.com", :encrypted_password => "$2a$10$pMM645kfsk7wZR9mdfqn/.bN2YunJsw9h9oSTVWpnViDuspJ5kG6a", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 1, :current_sign_in_at => "2013-01-27 23:28:59", :last_sign_in_at => "2013-01-27 23:28:59", :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1", :created_at => "2013-01-27 23:28:31", :updated_at => "2013-01-27 23:28:59", :name => "First User", :customer_id => nil, :last_4_digits => nil },
  { :email => "user2@example.com", :encrypted_password => "$2a$10$h4zOkgNhL.b9hvmuYJUflO1TS0jpivC9ub3m8uJcLjQeQ6ZuwIEfK", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 0, :current_sign_in_at => nil, :last_sign_in_at => nil, :current_sign_in_ip => nil, :last_sign_in_ip => nil, :created_at => "2013-01-27 23:28:31", :updated_at => "2013-01-27 23:28:31", :name => "Silver User", :customer_id => nil, :last_4_digits => nil },
  { :email => "user3@example.com", :encrypted_password => "$2a$10$w2tVWzwHswJMiLqIwnzt9.cfN5/oN4.lNqpMxV15tWsJSgzWMOa2q", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 0, :current_sign_in_at => nil, :last_sign_in_at => nil, :current_sign_in_ip => nil, :last_sign_in_ip => nil, :created_at => "2013-01-27 23:28:31", :updated_at => "2013-01-27 23:28:31", :name => "Gold User", :customer_id => nil, :last_4_digits => nil },
  { :email => "user4@example.com", :encrypted_password => "$2a$10$l1xT8aco6IvoHQxICt99UerjymYzZpmfu2m1Yymf95mp3.CvpXzPy", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 0, :current_sign_in_at => nil, :last_sign_in_at => nil, :current_sign_in_ip => nil, :last_sign_in_ip => nil, :created_at => "2013-01-27 23:28:32", :updated_at => "2013-01-27 23:28:32", :name => "Platinum User", :customer_id => nil, :last_4_digits => nil },
  { :email => "silver@stripe-test.com", :encrypted_password => "$2a$10$YnH5cDIY8Zf/ZgbrUSzuQO5aq0Dn2vrrYn8QnkE2LnyhIwfK2FdGK", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 1, :current_sign_in_at => "2013-01-27 23:29:55", :last_sign_in_at => "2013-01-27 23:29:55", :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1", :created_at => "2013-01-27 23:29:55", :updated_at => "2013-01-27 23:29:57", :name => "Silver", :customer_id => "cus_1BRlmV5zcrN3JT", :last_4_digits => "4242" },
  { :email => "gold@stripe-test.com", :encrypted_password => "$2a$10$zHYopvZhN8W4XhzAizkgbOKF0p/QWnH9ezseqn2pCU4wDAX8.tGFO", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 1, :current_sign_in_at => "2013-01-27 23:31:43", :last_sign_in_at => "2013-01-27 23:31:43", :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1", :created_at => "2013-01-27 23:31:43", :updated_at => "2013-01-27 23:31:44", :name => "Gold", :customer_id => "cus_1BRnMgX8uBEnVK", :last_4_digits => "4242" },
  { :email => "platinum@stripe-test.com", :encrypted_password => "$2a$10$Om/tAGgbg1cdoFJKXBtb5.oyiKuekA85sFp3xeV9pn77hFl4y2tie", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 1, :current_sign_in_at => "2013-01-27 23:33:22", :last_sign_in_at => "2013-01-27 23:33:22", :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1", :created_at => "2013-01-27 23:33:22", :updated_at => "2013-01-27 23:33:24", :name => "Platinum", :customer_id => "cus_1BRogcFKLufP0Q", :last_4_digits => "4242" }
], :without_protection => true )


