# encoding: utf-8

Exercise.create([
  { :title => "Scholar's mate", :description => "http://en.wikipedia.org /wiki/Scholar%27s_mate", :start => "a8-black-♜,b8-black-♞,c8-black-♝,d8-black-♛,e8-black-♚,f8-black-♝,g8-black-♞,h8-black-♜,a7-black-♟,b7-black-♟,c7-black-♟,d7-black-♟,e7-black-♟,f7-black-♟,g7-black-♟,h7-black-♟,a2-white-♟,b2-white-♟,c2-white-♟,d2-white-♟,e2-white-♟,f2-white-♟,g2-white-♟,h2-white-♟,a1-white-♜,b1-white-♞,c1-white-♝,d1-white-♛,e1-white-♚,f1-white-♝,g1-white-♞,h1-white-♜", :created_at => "2012-11-09 22:06:04", :updated_at => "2012-12-11 03:59:14", :lesson_id => 3 },
  { :title => "Fool's mate", :description => "http://en.wikipedia.org/wiki/Fool%27s_Mate", :start => "a8-black-♜,b8-black-♞,c8-black-♝,d8-black-♛,e8-black-♚,f8-black-♝,g8-black-♞,h8-black-♜,a7-black-♟,b7-black-♟,c7-black-♟,d7-black-♟,e7-black-♟,f7-black-♟,g7-black-♟,h7-black-♟,a2-white-♟,b2-white-♟,c2-white-♟,d2-white-♟,e2-white-♟,f2-white-♟,g2-white-♟,h2-white-♟,a1-white-♜,b1-white-♞,c1-white-♝,d1-white-♛,e1-white-♚,f1-white-♝,g1-white-♞,h1-white-♜", :created_at => "2012-11-09 22:07:09", :updated_at => "2012-12-11 05:20:20", :lesson_id => 3 },
  { :title => "Pawn Movement", :description => "This is the description of how a pawn moves", :start => "e7-black-♟,d4-white-♟", :created_at => "2012-11-09 22:08:06", :updated_at => "2012-12-11 21:29:12", :lesson_id => 4 },
  { :title => "The King's Defense", :description => "Unlike most of the openings in this book, the King’s defense doesn’t rely upon your opponent’s moves. In exchange for being patient, all of your pieces are well defended throughout the opening. This opening is recommended against novice opponents that are overly aggressive. Let them remove their own defenses for you, while your king is tucked away safely. There are faster defenses, but the King’s Defense has a n added element of center control. This will allow more powerful attacks later on in the game. ", :start => "a8-black-♜,b8-black-♞,c8-black-♝,d8-black-♛,e8-black-♚,f8-black-♝,g8-black-♞,h8-black-♜,a7-black-♟,b7-black-♟,c7-black-♟,d7-black-♟,e7-black-♟,f7-black-♟,g7-black-♟,h7-black-♟,a2-white-♟,b2-white-♟,c2-white-♟,d2-white-♟,e2-white-♟,f2-white-♟,g2-white-♟,h2-white-♟,a1-white-♜,b1-white-♞,c1-white-♝,d1-white-♛,e1-white-♚,f1-white-♝,g1-white-♞,h1-white-♜", :created_at => "2012-11-21 03:31:28", :updated_at => "2012-11-30 04:24:25", :lesson_id => 1 },
  { :title => "The Ruy Lopez ", :description => "The Ruy Lopez is one of the most popular “open game” attacks in modern chess. Open game simply means a game where white and black both move their king’s side pawn first. This opening flows naturally from this first move, providing excellent center control, a swift attack, and the option for a castle early on. It’s likely that novice opponents will make mistakes in the opening. We’ll show the best moves for black, but if your opponent does not follow these moves, remember to immediately take any unprotected pieces. If black’s pieces are well defended, simply move on to complete the Ruy Lopez.", :start => "a8-black-♜,b8-black-♞,c8-black-♝,d8-black-♛,e8-black-♚,f8-black-♝,g8-black-♞,h8-black-♜,a7-black-♟,b7-black-♟,c7-black-♟,d7-black-♟,e7-black-♟,f7-black-♟,g7-black-♟,h7-black-♟,a2-white-♟,b2-white-♟,c2-white-♟,d2-white-♟,e2-white-♟,f2-white-♟,g2-white-♟,h2-white-♟,a1-white-♜,b1-white-♞,c1-white-♝,d1-white-♛,e1-white-♚,f1-white-♝,g1-white-♞,h1-white-♜", :created_at => "2012-11-23 04:25:07", :updated_at => "2012-12-11 21:19:41", :lesson_id => 1 },
  { :title => "The Caro-Kann Defense ", :description => "My personal favorite, this opening is played as black. The Caro-Kann defense is actually an attack that can punish opponents for mistakes more than any other opening in this book. Before their fourth turn, a novice opponent may have already lost their most important pawn and therefore control of the entire center.The downside to this aggressive defense is king safety. The king can eventually castle to either side with this defense, but a castle would take at least three more moves after the opening. But hey, the safest king is the king that wins.", :start => "a8-black-♜,b8-black-♞,c8-black-♝,d8-black-♛,e8-black-♚,f8-black-♝,g8-black-♞,h8-black-♜,a7-black-♟,b7-black-♟,c7-black-♟,d7-black-♟,e7-black-♟,f7-black-♟,g7-black-♟,h7-black-♟,a2-white-♟,b2-white-♟,c2-white-♟,d2-white-♟,e2-white-♟,f2-white-♟,g2-white-♟,h2-white-♟,a1-white-♜,b1-white-♞,c1-white-♝,d1-white-♛,e1-white-♚,f1-white-♝,g1-white-♞,h1-white-♜", :created_at => "2012-11-23 04:25:07", :updated_at => "2012-11-30 04:24:54", :lesson_id => 1 },
  { :title => "Queen's Gambit", :description => "The Queen’s gambit is a fun and powerful attack, played as white, that can easily outwit novice opponents. In almost the opposite approach of the Kann defense, the Queen’s gambit gives black a chance to take a pawn early on. After a few moves, however, it becomes apparent that white can take revenge on the same black pawn after isolating it from any defenders. This can be one of the more difficult openings to understand strategically. Take your time working through it. The benefits of understanding this subtle strategy will be well worth the effort.", :start => "a8-black-♜,b8-black-♞,c8-black-♝,d8-black-♛,e8-black-♚,f8-black-♝,g8-black-♞,h8-black-♜,a7-black-♟,b7-black-♟,c7-black-♟,d7-black-♟,e7-black-♟,f7-black-♟,g7-black-♟,h7-black-♟,a2-white-♟,b2-white-♟,c2-white-♟,d2-white-♟,e2-white-♟,f2-white-♟,g2-white-♟,h2-white-♟,a1-white-♜,b1-white-♞,c1-white-♝,d1-white-♛,e1-white-♚,f1-white-♝,g1-white-♞,h1-white-♜", :created_at => "2012-11-23 04:25:07", :updated_at => "2012-11-30 04:25:06", :lesson_id => 1 },
  { :title => "The Nim Defense", :description => "This defense takes advantage of a topic we have not yet discussed, a “pin.” Check out the section on Pins and Forks for more information. Unlike the Queen’s gambit, this opening does not depend on taking the center immediately. Instead it allows white to take the center in exchange for an exposed white king. Exploiting this weak king will give us a huge amount of control over the movements of white’s pieces for the middle part of the game. This opening also forces white to respond, giving them plenty of chances to make a mistake or two.", :start => "a8-black-♜,b8-black-♞,c8-black-♝,d8-black-♛,e8-black-♚,f8-black-♝,g8-black-♞,h8-black-♜,a7-black-♟,b7-black-♟,c7-black-♟,d7-black-♟,e7-black-♟,f7-black-♟,g7-black-♟,h7-black-♟,a2-white-♟,b2-white-♟,c2-white-♟,d2-white-♟,e2-white-♟,f2-white-♟,g2-white-♟,h2-white-♟,a1-white-♜,b1-white-♞,c1-white-♝,d1-white-♛,e1-white-♚,f1-white-♝,g1-white-♞,h1-white-♜", :created_at => "2012-11-23 04:25:07", :updated_at => "2012-12-07 22:09:15", :lesson_id => 1 },
  { :title => "New King's Defense", :description => "This is a very high-tempo defense. It can be used in just about any situation as either white or black. In fact, the new king’s defense can actually be used after many other openings. If you find yourself in an odd situation and don’t know how to continue, the new king’s defense is a fantastic way to protect the king while quietly advancing your minor pieces.", :start => "a8-black-♜,b8-black-♞,c8-black-♝,d8-black-♛,e8-black-♚,f8-black-♝,g8-black-♞,h8-black-♜,a7-black-♟,b7-black-♟,c7-black-♟,d7-black-♟,e7-black-♟,f7-black-♟,g7-black-♟,h7-black-♟,a2-white-♟,b2-white-♟,c2-white-♟,d2-white-♟,e2-white-♟,f2-white-♟,g2-white-♟,h2-white-♟,a1-white-♜,b1-white-♞,c1-white-♝,d1-white-♛,e1-white-♚,f1-white-♝,g1-white-♞,h1-white-♜", :created_at => "2012-11-23 04:25:07", :updated_at => "2012-11-30 04:25:20", :lesson_id => 1 }
], :without_protection => true )



Lesson.create([
  { :title => "Openings", :description => "This is a lesson all about openings", :created_at => "2012-11-29 03:19:24", :updated_at => "2012-11-29 03:19:24" },
  { :title => "Basic Mates", :description => "Some simple Checkmates", :created_at => "2012-11-30 04:23:23", :updated_at => "2012-11-30 04:23:23" },
  { :title => "Basic Moves", :description => "", :created_at => "2012-12-02 04:01:43", :updated_at => "2012-12-02 04:01:43" }
], :without_protection => true )



Move.create([
  { :piece => "♟", :starting_coordinate => "e2", :ending_coordinate => "e4", :explanation => "Pawn goes e2 to e4", :created_at => "2012-11-12 01:33:04", :updated_at => "2012-11-12 21:14:56", :exercise_id => 1, :move_number => 1, :computer => nil },
  { :piece => "♟", :starting_coordinate => "e7", :ending_coordinate => "e5", :explanation => "Pawn goes from e7 to e5", :created_at => "2012-11-12 21:05:31", :updated_at => "2012-11-14 02:06:48", :exercise_id => 1, :move_number => 2, :computer => nil },
  { :piece => "♛", :starting_coordinate => "d1", :ending_coordinate => "h5", :explanation => "Queen goes from d1 to h5", :created_at => "2012-11-12 21:06:27", :updated_at => "2012-11-12 21:19:03", :exercise_id => 1, :move_number => 3, :computer => nil },
  { :piece => "♞", :starting_coordinate => "b8", :ending_coordinate => "c6", :explanation => "Knight goes b8 to c6", :created_at => "2012-11-12 21:07:10", :updated_at => "2012-11-12 21:19:09", :exercise_id => 1, :move_number => 4, :computer => nil },
  { :piece => "♝", :starting_coordinate => "f1", :ending_coordinate => "c4", :explanation => "Bishop goes f1 to c4", :created_at => "2012-11-12 21:07:35", :updated_at => "2012-11-12 21:19:18", :exercise_id => 1, :move_number => 5, :computer => nil },
  { :piece => "♞", :starting_coordinate => "g8", :ending_coordinate => "f6", :explanation => "Knight goes g8 to f6", :created_at => "2012-11-12 21:07:58", :updated_at => "2012-11-12 21:19:25", :exercise_id => 1, :move_number => 6, :computer => nil },
  { :piece => "♛", :starting_coordinate => "h5", :ending_coordinate => "f7", :explanation => "Queen goes h5 to f7 for checkmate", :created_at => "2012-11-12 21:08:31", :updated_at => "2012-11-12 21:19:32", :exercise_id => 1, :move_number => 7, :computer => nil },
  { :piece => "♟", :starting_coordinate => "d4", :ending_coordinate => "d5", :explanation => "Can move straight ahead", :created_at => "2012-11-18 00:38:42", :updated_at => "2012-11-18 00:38:42", :exercise_id => 3, :move_number => 1, :computer => nil },
  { :piece => "♟", :starting_coordinate => "d5", :ending_coordinate => "d6", :explanation => "Pawn moves forward", :created_at => "2012-11-18 00:39:15", :updated_at => "2012-11-18 00:39:15", :exercise_id => 3, :move_number => 2, :computer => nil },
  { :piece => "♟", :starting_coordinate => "d6", :ending_coordinate => "e7", :explanation => "Pawn captures in with diagonal move", :created_at => "2012-11-18 00:40:00", :updated_at => "2012-11-18 00:40:00", :exercise_id => 3, :move_number => 3, :computer => nil },
  { :piece => "♟", :starting_coordinate => "e2", :ending_coordinate => "e4", :explanation => "In this opening we are white. We start by moving the king’s side pawn forward two spaces. The downside of moving the king’s pawn forward is that the pawn is not automatically protected like the queen’s pawn is. Protecting this pawn will be one of the purposes of our next move ", :created_at => "2012-11-21 03:50:20", :updated_at => "2012-11-21 03:50:20", :exercise_id => 4, :move_number => 1, :computer => nil },
  { :piece => "♟", :starting_coordinate => "d2", :ending_coordinate => "d3", :explanation => "Regardless of what black does, this next move both protects the forward pawn and frees up room for white’s left knight to protect the king later on. So far no minor pieces have been moved, but there is a fair amount of center control with the pawns", :created_at => "2012-11-21 03:50:20", :updated_at => "2012-11-21 03:50:20", :exercise_id => 4, :move_number => 2, :computer => nil },
  { :piece => "♞", :starting_coordinate => "g1", :ending_coordinate => "f3", :explanation => "The knight moves forward to bring the king closer to castling. This also puts a little more pressure on the center. Don’t be afraid to make fast work of any pieces that fall into the knight’s range without protection. ", :created_at => "2012-11-21 03:50:20", :updated_at => "2012-11-21 03:50:20", :exercise_id => 4, :move_number => 3, :computer => nil },
  { :piece => "♞", :starting_coordinate => "b1", :ending_coordinate => "d2", :explanation => "This move does three things: 1) It links the knights so that they protect each other. 2) It advances another minor piece in a way that protects the center pawn. 3) It protects the king from any diagonal attacks. With this you are ready to get the bishop out of the way so that the king can castle, completing the defense. ", :created_at => "2012-11-21 03:50:20", :updated_at => "2012-11-21 03:50:20", :exercise_id => 4, :move_number => 4, :computer => nil },
  { :piece => "♟", :starting_coordinate => "g2", :ending_coordinate => "g3", :explanation => "There are two ways to get the bishop out and complete the castle. While moving out to the left (e2) would be faster, this would completely block in the queen as well as prevent the bishop from attacking the center later on. Over thousands of games, it is statistically better to move this pawn first, then the bishop to the right (g2). This has the added advantage of a perfect defensive pawn position around the king.", :created_at => "2012-11-21 03:50:20", :updated_at => "2012-11-21 03:51:52", :exercise_id => 4, :move_number => 5, :computer => nil },
  { :piece => "♝", :starting_coordinate => "f1", :ending_coordinate => "g2", :explanation => "The defense is almost complete. Every single white piece is protected by another, and with a good deal of center control as well. Again, notice the positioning of the pawns on the side that we will castle to. If none of the pawns had been moved forward, our king would be trapped on a single file. We also do not want to move the pawns up too far. The ideal position is one in which the king can both protect the pawns and escape from attacks.", :created_at => "2012-11-21 03:50:20", :updated_at => "2012-11-21 03:50:20", :exercise_id => 4, :move_number => 6, :computer => nil },
  { :piece => "♜", :starting_coordinate => "h1", :ending_coordinate => "f1", :explanation => "", :created_at => "2012-11-21 03:50:20", :updated_at => "2012-11-21 03:50:20", :exercise_id => 4, :move_number => 7, :computer => nil },
  { :piece => "♚", :starting_coordinate => "e1", :ending_coordinate => "g1", :explanation => "The final move in the defense is the kings side castle. This is done by moving the king two spaces towards a rook, assuming nothing is between them. The rook is then moved to the opposite side of the king, essentially freeing the rook to attack while protecting the king. Castling can only be done if neither the king nor the rook has moved yet this game. ", :created_at => "2012-11-21 03:50:20", :updated_at => "2012-11-21 03:50:20", :exercise_id => 4, :move_number => 8, :computer => nil },
  { :piece => "♟", :starting_coordinate => "e2", :ending_coordinate => "e4", :explanation => "In this opening we are white. As with the king’s defense opening, we start by moving the king’s pawn forward. Notice any aggressive options that moving this pawn gives us? We will take advantage of one of these options later on. ", :created_at => "2012-11-23 04:29:42", :updated_at => "2012-12-11 00:42:36", :exercise_id => 5, :move_number => 1, :computer => nil },
  { :piece => "♟", :starting_coordinate => "e7", :ending_coordinate => "e5", :explanation => "When black mirrors white’s play by also moving up the king’s pawn, we call this an “open game.” This Ruy Lopez attack can still be used against some other openings by black, but make sure your front pawn is never under attack without proper defense (for example, if black moved the knight from g8 to f6 our pawn would need to move forward or be defended before making the next move).", :created_at => "2012-11-23 04:29:42", :updated_at => "2012-12-12 23:11:35", :exercise_id => 5, :move_number => 2, :computer => true },
  { :piece => "♞", :starting_coordinate => "g1", :ending_coordinate => "f3", :explanation => "Now we put pressure on black’s first center pawn. This will also open up the lane for a castle later on. Notice that this blocks in the pawn on f2. Moving the knight is still a great tempo move because we need that pawn exactly where it is now to protect the king, but in other openings this is something to consider when moving the knight.", :created_at => "2012-11-23 04:29:42", :updated_at => "2012-12-11 00:43:17", :exercise_id => 5, :move_number => 3, :computer => nil },
  { :piece => "♞", :starting_coordinate => "b8", :ending_coordinate => "c6", :explanation => "Black makes a good high tempo move, both advancing a minor piece and protecting the pawn. Little do they know this is playing right into our trap. If black makes a different move at this point, one of our options is to move the queen’s pawn forward two spaces for fantastic center control under the protection of the knight and queen. ", :created_at => "2012-11-23 04:29:42", :updated_at => "2012-12-12 23:12:38", :exercise_id => 5, :move_number => 4, :computer => true },
  { :piece => "♝", :starting_coordinate => "f1", :ending_coordinate => "b5", :explanation => "We spring our trap. The bishop comes out from across the board to start a pin on the knight. While the knight is not technically pinned (unable to move because it is protecting the king), the knight will become pinned if black tried to take the center with their queen-side pawn. The pressure this attack puts on your opponent is perfect for most home games. Forcing your opponent to react with aggressive play will eventually force them into making an error. ", :created_at => "2012-11-23 04:29:42", :updated_at => "2012-12-11 00:43:42", :exercise_id => 5, :move_number => 5, :computer => nil },
  { :piece => "♟", :starting_coordinate => "e2", :ending_coordinate => "e4", :explanation => "", :created_at => "2012-11-23 04:29:42", :updated_at => "2012-11-23 04:29:42", :exercise_id => 6, :move_number => 1, :computer => nil },
  { :piece => "♟", :starting_coordinate => "c7", :ending_coordinate => "c6", :explanation => "In this opening we are black. We start with an inconspicuous first move. Will white be prepared for the hidden attack? ", :created_at => "2012-11-23 04:29:42", :updated_at => "2012-11-23 04:29:42", :exercise_id => 6, :move_number => 2, :computer => nil },
  { :piece => "♟", :starting_coordinate => "d2", :ending_coordinate => "d4", :explanation => "This is the best move for white. If they try something else, most other moves will only make our attack more powerful. Keep counting defenders and use common sense to take control of the center.", :created_at => "2012-11-23 04:29:42", :updated_at => "2012-11-23 04:29:42", :exercise_id => 6, :move_number => 3, :computer => nil },
  { :piece => "♟", :starting_coordinate => "d7", :ending_coordinate => "d5", :explanation => "A menacing attack opens up in the center. Trading with black’s pawn would put white at a disadvantage, so this is not a good move for white. Instead, white may try to protect the pawn. If the white pawn on 4e isn’t protected by next turn, take it and claim a solid advantage.", :created_at => "2012-11-23 04:29:42", :updated_at => "2012-11-23 04:29:42", :exercise_id => 6, :move_number => 4, :computer => nil },
  { :piece => "♞", :starting_coordinate => "b1", :ending_coordinate => "c3", :explanation => "This is the favorite move for white. The reasons should appear obvious. This knight protects white’s pawn while simultaneously putting pressure on black’s center pawn. Unfortunately for white, we have bigger things in mind.", :created_at => "2012-11-23 04:29:42", :updated_at => "2012-11-23 04:29:42", :exercise_id => 6, :move_number => 5, :computer => nil },
  { :piece => "♟", :starting_coordinate => "d5", :ending_coordinate => "e4", :explanation => "This is the first time in the openings we’ve looked at that a player chooses to take a piece that is adequately defended. You’ll see with black’s next move a perfect example of the kind of set-up where it is smart to take an even trade with a defended enemy piece. Can you spot the trap? ", :created_at => "2012-11-23 04:29:42", :updated_at => "2012-11-23 04:29:42", :exercise_id => 6, :move_number => 6, :computer => nil },
  { :piece => "♞", :starting_coordinate => "c3", :ending_coordinate => "e4", :explanation => "White has to take black’s pawn or be down by one point and a massive amount of center control. It’s an even trade for white, so the decision should be a quick one. Black’s next move concludes the opening, forcing white into several difficult decisions.", :created_at => "2012-11-23 04:29:42", :updated_at => "2012-11-23 04:29:42", :exercise_id => 6, :move_number => 7, :computer => nil },
  { :piece => "♝", :starting_coordinate => "c8", :ending_coordinate => "f5", :explanation => "The open center is easy feeding ground for this early bishop. White must choose to defend the knight or lose valuable tempo moving the knight out of danger. Keep an eye out for which side white is planning to castle on and plan your attack accordingly.", :created_at => "2012-11-23 04:29:42", :updated_at => "2012-11-23 04:29:42", :exercise_id => 6, :move_number => 8, :computer => nil },
  { :piece => "♟", :starting_coordinate => "d2", :ending_coordinate => "d4", :explanation => "Called a “closed game”, we (white) start by moving the queen’s pawn forward by two. Both closed and open game opening attacks have been studied in this book. Take some time to think about the different options available for every piece when moving the queen’s pawn as compared to the king’s pawn.", :created_at => "2012-11-23 04:29:42", :updated_at => "2012-11-23 04:29:42", :exercise_id => 7, :move_number => 1, :computer => nil },
  { :piece => "♟", :starting_coordinate => "d7", :ending_coordinate => "d5", :explanation => "This is the expected move from black. If they make a more defensive move, then we cannot continue this opening. Unless it would be under attack, the best move against a player that makes a more defensive move is for us to advance the king’s pawn on e2 to e4. If black does make the above move then we are ready to offer them the Queen’s gambit.", :created_at => "2012-11-23 04:29:42", :updated_at => "2012-11-23 04:29:42", :exercise_id => 7, :move_number => 2, :computer => nil },
  { :piece => "♟", :starting_coordinate => "c2", :ending_coordinate => "c4", :explanation => "A gambit is a risk taken in the hopes of greater rewards. With this move we offer black a chance to take our pawn, knowing that this one-time loss in pieces will turn into a big-time gain in center control.", :created_at => "2012-11-23 04:29:42", :updated_at => "2012-11-23 04:29:42", :exercise_id => 7, :move_number => 3, :computer => nil },
  { :piece => "♟", :starting_coordinate => "d5", :ending_coordinate => "c4", :explanation => "Black takes the unguarded pawn. But this isolates the black pawn, making it an easy target in the future. What do you think white’s next move should be? Taking center control and opening an attack on the black pawn are both priorities here.", :created_at => "2012-11-23 04:29:42", :updated_at => "2012-11-23 04:29:42", :exercise_id => 7, :move_number => 4, :computer => nil },
  { :piece => "♟", :starting_coordinate => "e2", :ending_coordinate => "e4", :explanation => "The most efficient and therefore most powerful move is to push the king’s side pawn into the center. This allows the bishop to attack black’s pawn at any time. The black pawn has nowhere to escape. This means there is no use in capturing it right away. Instead, we will continue to press our advantage in the center and wait until the dust has settled to take black’s pawn.", :created_at => "2012-11-23 04:29:42", :updated_at => "2012-11-23 04:29:42", :exercise_id => 7, :move_number => 5, :computer => nil },
  { :piece => "♟", :starting_coordinate => "e7", :ending_coordinate => "e5", :explanation => "This is the best follow-up by black. It brings up the strongest center pawn black has and attempts to re-take the center. However, there is an easy way to both protect our pawn and put black’s under further attack. If your opponent makes at different move at this point, simply protect your pieces in the center and eventually take the black pawn on c4.  Why do we not want to take black’s pawn with our own? It is much better to have pawns side by side than one in front of the other. If we were to take black’s pawn, our center pawns could no longer protect each other.", :created_at => "2012-11-23 04:29:42", :updated_at => "2012-11-23 04:29:42", :exercise_id => 7, :move_number => 6, :computer => nil },
  { :piece => "♟", :starting_coordinate => "g1", :ending_coordinate => "f3", :explanation => "This is a much better option than taking black’s pawn. Protecting our center pawn and bringing a minor piece to the front will greatly increase our command of the center of the board and the rest of the game. ", :created_at => "2012-11-23 04:29:42", :updated_at => "2012-11-23 04:29:42", :exercise_id => 7, :move_number => 7, :computer => nil },
  { :piece => "♟", :starting_coordinate => "d2", :ending_coordinate => "d4", :explanation => "We are black in this opening. This is our defense against a white player that moves the queen’s pawn first. This opening would also work very well against the Queen’s Gambit. Pay attention to this opening so that you can see it coming when someone tries to use it against you.", :created_at => "2012-11-23 04:29:42", :updated_at => "2012-11-23 04:29:42", :exercise_id => 8, :move_number => 1, :computer => nil },
  { :piece => "♞", :starting_coordinate => "g8", :ending_coordinate => "f6", :explanation => "This is the first move for black. You will also see this move in our next and final opening. While we call this opening a defense, you will soon see the attack potential develop.", :created_at => "2012-11-23 04:29:42", :updated_at => "2012-11-23 04:29:42", :exercise_id => 8, :move_number => 2, :computer => nil },
  { :piece => "♟", :starting_coordinate => "c2", :ending_coordinate => "c4", :explanation => "White advances like they would in the Queen’s gambit. Notice that white cannot move the king’s pawn forward two spaces, because our knight would capture it for free. There are a few other moves white could do at this point, but for the most part our next moves will stay the same regardless.", :created_at => "2012-11-23 04:29:42", :updated_at => "2012-11-23 04:29:42", :exercise_id => 8, :move_number => 3, :computer => nil },
  { :piece => "♟", :starting_coordinate => "e7", :ending_coordinate => "e6", :explanation => "Our king side pawn is moved up one space. Obviously, immediate center control is not what we are fighting for. Instead, we will use our minor pieces to pin white and pick away at unprotected pawns.", :created_at => "2012-11-23 04:29:42", :updated_at => "2012-11-23 04:29:42", :exercise_id => 8, :move_number => 4, :computer => nil },
  { :piece => "♞", :starting_coordinate => "b1", :ending_coordinate => "c3", :explanation => "This is the most common follow-up move for white. They continue to press the center with either knight or the pawns. Can you spot the “pin” that is about to occur? White’s insatiable greed for the center has given us an opening.", :created_at => "2012-11-23 04:29:42", :updated_at => "2012-11-23 04:29:42", :exercise_id => 8, :move_number => 5, :computer => nil },
  { :piece => "♝", :starting_coordinate => "f8", :ending_coordinate => "b4", :explanation => "Even though white’s knight is technically defended, it is unable to move since this would expose the king to our bishop. White will need to keep making only the right decisions or this game is going to end quickly.", :created_at => "2012-11-23 04:29:42", :updated_at => "2012-11-23 04:29:42", :exercise_id => 8, :move_number => 6, :computer => nil },
  { :piece => "♞", :starting_coordinate => "g1", :ending_coordinate => "f3", :explanation => "We are white in this example. The new king’s defense starts by moving the knight on the king’s side. When played as white, this will limit black’s options, as they can no longer move their king’s side pawn forward two spaces. If a novice opponent does make this mistake, make sure to simply snatch up the undefended pawn before continuing. ", :created_at => "2012-11-23 04:29:42", :updated_at => "2012-11-23 04:29:42", :exercise_id => 9, :move_number => 1, :computer => nil },
  { :piece => "♟", :starting_coordinate => "g2", :ending_coordinate => "g3", :explanation => "We will ignore black’s moves because there is nothing that can realistically pose a threat to our progression. For move two we move the pawn on g3 up one. Why not up two? This is a defense and we intend to castle the king to this side. While moving the pawn up two would still allow the bishop to escape, it would leave the king far too vulnerable.", :created_at => "2012-11-23 04:29:42", :updated_at => "2012-11-23 04:29:42", :exercise_id => 9, :move_number => 2, :computer => nil },
  { :piece => "♝", :starting_coordinate => "f1", :ending_coordinate => "g2", :explanation => "The  third move clears space for the king to castle. Some time after the opening, we will need to move the knight forward, freeing the bishop.", :created_at => "2012-11-23 04:29:42", :updated_at => "2012-11-23 04:29:42", :exercise_id => 9, :move_number => 3, :computer => nil },
  { :piece => "♜", :starting_coordinate => "h1", :ending_coordinate => "f1", :explanation => "", :created_at => "2012-11-23 04:29:42", :updated_at => "2012-11-23 04:29:42", :exercise_id => 9, :move_number => 4, :computer => nil },
  { :piece => "♚", :starting_coordinate => "e1", :ending_coordinate => "g1", :explanation => "Our new king’s defense ends with the castle. The king couldn’t be more safe! Let novice opponents make risky attacks and when they prove futile we can use our full army in a concentrated effort, knowing that our king is already secure.", :created_at => "2012-11-23 04:29:42", :updated_at => "2012-11-23 04:29:42", :exercise_id => 9, :move_number => 5, :computer => nil }
], :without_protection => true )


# #populates inital admin user
# puts 'ROLES'
# YAML.load(ENV['ROLES']).each do |role|
#   Role.find_or_create_by_name({ :name => role }, :without_protection => true)
#   puts 'role: ' << role
# end
# puts 'DEFAULT USERS'
# user = User.find_or_create_by_email :name => ENV['ADMIN_NAME'].dup, :email => ENV['ADMIN_EMAIL'].dup, :password => ENV['ADMIN_PASSWORD'].dup, :password_confirmation => ENV['ADMIN_PASSWORD'].dup
# puts 'user: ' << user.name
# user.add_role :admin